package gconstant

const (
	DOT              = "."
	COMMA            = ","
	SEMICOLON        = ""
	COLON            = ":"
	AET              = "@"
	HLINE            = "-"
	UNDERLINE        = "_"
	EMPTY            = ""
	BracketLeft      = "["
	BracketRight     = "]"
	BraceLeft        = "{"
	BraceRight       = "}"
	ParenthesisLeft  = "("
	ParenthesisRight = ")"
	SPRIT            = "/"
	AND              = "&"
	QUESTION         = "?"
	EQUAL            = "="
	PROTOCOL         = "://"
	HTTP             = "http://"
	HTTPS            = "https://"
	LF               = "\n"
	CR               = "\r"
	SPACE            = " "
)
